# Generated by Django 4.2.2 on 2023-07-13 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='price',
            field=models.FloatField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
