# Generated by Django 4.2.2 on 2023-07-13 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='price',
        ),
    ]
