# Generated by Django 4.2.3 on 2023-07-13 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_car_speed_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
